version: "2"

run:
  timeout: 5m

linters:
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close
        - os.Remove
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - misspell
    - noctx
    - bodyclose
